meyzel/meyzel/Controllers/MekanlarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using meyzel.Models;

namespace meyzel.Controllers
{
    [Authorize]
    public class MekanlarController : Controller
    {
        private MeyzelDBEntities db = new MeyzelDBEntities();
       
        // GET: Mekanlar
        public ActionResult Index()
        {
            return View(db.Mekanlar.ToList());
        }

        // GET: Mekanlar/Details/5
        public ActionResult Details(int? id)
        {
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mekanlar mekanlar = db.Mekanlar.Find(id);
            
            if (mekanlar == null)
            {
                return HttpNotFound();
            }
            ViewBag.yorumlar = db.Yorumlar.Where(s => s.MekanID == id).ToList();
            return View(mekanlar);
        }

        // POST: Yorumlars/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(Yorumlar yorums)
        {
            if (ModelState.IsValid)
            {
                db.Yorumlar.Add(yorums);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: Mekanlar/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Mekanlar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "mekanID,mekanAdi,mekanAciklama,UlkeAdi,IlAdi,IlceAdi,mekanEtiket,mekanRaiting")] Mekanlar mekanlar)
        {
            if (ModelState.IsValid)
            {
                db.Mekanlar.Add(mekanlar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mekanlar);
        }

        // GET: Mekanlar/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mekanlar mekanlar = db.Mekanlar.Find(id);
            if (mekanlar == null)
            {
                return HttpNotFound();
            }
            return View(mekanlar);
        }

        // POST: Mekanlar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "mekanID,mekanAdi,mekanAciklama,UlkeAdi,IlAdi,IlceAdi,mekanEtiket,mekanRaiting")] Mekanlar mekanlar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mekanlar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mekanlar);
        }

        // GET: Mekanlar/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mekanlar mekanlar = db.Mekanlar.Find(id);
            if (mekanlar == null)
            {
                return HttpNotFound();
            }
            return View(mekanlar);
        }

        // POST: Mekanlar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Mekanlar mekanlar = db.Mekanlar.Find(id);
            db.Mekanlar.Remove(mekanlar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

meyzel/meyzel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MeyZel", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Anasayfa", "Index", "Home")</li>
                    <li>@Html.ActionLink("En Çok Beğenilenler", "Index", "Mekanlar")</li>
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>       
    </div>
      
    
    
      @RenderBody()
  
        

  <footer class="foot-model">
      <div class="col-md-3 col-xs-4"> 
          <i class="fa fa-address-book" aria-hidden="true"></i>
          <strong>Sosyal Bağlantılar</strong> <br />
          <i class="fa fa-instagram fa-5x fa-hover" aria-hidden="true"></i>
          <i class="fa fa-facebook-official fa-5x fa-hover" aria-hidden="true"></i>
          <i class="fa fa-twitter fa-5x fa-hover" aria-hidden="true"></i>
          <i class="fa fa-android fa-5x fa-hover" aria-hidden="true"></i>  
      </div>
      <div class="col-md-1">
          
      </div>
      <div class="col-md-5 col-xs-4">
          <i class="fa fa-link" aria-hidden="true"></i>
          <strong>Site Haritası</strong> <br />
          <ul class="linkler"> 
              <li><a href="Home/Index">Anasayfa</a></li>
              <li><a href="Home/Index">En Çok Beğenilenler</a>
              <ul>
                  <li><a href="Home/Index">Konser Alanı</a></li>
                  <li><a href="Home/Index">Tiyatro Salonu</a></li>
                  <li><a href="Home/Index">Sinema Salonu</a></li>
                  <li><a href="Home/Index">Lunapark</a></li>
              </ul>
              </li>   
          </ul>           
      </div>
      <div class="col-md-1"></div>
      <div class="col-md-2 col-xs-4">
          <i class="fa fa-user-circle-o" aria-hidden="true"></i>
          <strong>Hakkımızda</strong> <br />
          <p>İsim: İlayda Özdemir. <br />
             Numara: g151210106. <br />
             Okul: Sakarya Uni.
             Sınıf: 2.Öğretim - B grubu</p>
      </div>

  </footer>  
 
       

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>